### ISSUE TITLE
Question: what if matrix2d?

### ISSUE THREAD

**Issue by thednp** [mattdesl/mat4-decompose#2]
Haven't checked (n00b me)... what if I invoke this to a result of computed style (properly parsed to this code's requirements), but the matrix is not matrix3d, but matrix. What would happen? Would it return false or try to decompose?

Thank you

**Comment by mattdesl** [comment]
Bad things will happen. :stuck_out_tongue_closed_eyes: 

It only supports 4x4 matrices, i.e. a flat 16-element array.

**Comment by mattdesl** [comment]
However you can treat a `matrix()` as a `matrix3d()` (4x4) like I do here:

https://www.npmjs.com/package/mat4-css-parse

``` js
var parse = require('mat4-css-parse')
var decompose = require('mat4-decompose')

var style = window.getComputedStyle(element, null)
var matrix = parse(style.tranfsorm)
decompose(matrix, translation, scale, ...etc) 
```

**Comment by thednp** [comment]
Thanks for reply. Excellent work in everything you do :)

**Comment by thednp** [comment]
One more quick question: I need something to compose matrix from my objects:

```
transform : {
   translate : {
      translateX : {value: 250, unit: 'px'},
      translateY : {value: 0, unit: 'px'},
      translateZ : {value: 0, unit: 'px'},
   },
   skew : {}, // same as above
   rotate: {} // same
}
```

I am sorry for asking this kind of totally n00b questions, but I have no clue and I need something like this, and by the way, I ask you because this seems to me to be the best code.

**Comment by mattdesl** [comment]
I don't have anything exactly like that but this is pretty close: 
https://github.com/mattdesl/css-mat4

**Comment by thednp** [comment]
Thanks again, I missed that, now starred it :)
