### ISSUE TITLE
Computed values are incorrect

### ISSUE THREAD

**Issue by thednp** [mattdesl/mat4-decompose#3]
Hello, remember me? I'm no n00b anymore =) 

I've tested a couple scripts to do unmatrix/decompose and yours is the only one that actually gets translation right. I need something like this to make a matrix animation for my KUTE.js, so far nothing reliable.

**My problem**
Have the following example
```markup
<div class="xample" style="transform: perspective(400px) rotateX(45deg) translateY(170px)">3D</div>
```
The result of the decompose function for the above
```js
transform = {
 perspective: (4) [0, -0.0017677700379863381, -0.0017677700379863381, 1]
 quaternion: (4) [0.3826834323650898, 0, 0, 0.9238795325112867]
 scale: (3) [1, 1.0000003200605172, 1.0000003200605172]
 skew: (3) [0, 0, 0]
 translation: (3) [0, 170, 0]
}
```
Now, the translation is right, but the rotation is less than half the input value (~ 22deg = 0.38268*180/Math.PI) and the perspective is off by about 165 (~565 = -1/-0.01767).

**Questions:**
* what if we recalculate the quaternion matrix with a q[3] of 1, would this solve the incorrect rotation quaterion?
* is this something to do with the new implementation of `DOMMatrix()` API to replace the old `CSSMatrix`?
* does this have to do with Euler vs quaternion calculation of rotation?
* what if we decompose the matrix by dividing functions one-by-one, the reverse process of multiplication, do you think this would work?
* do you plan on updating the code?

**Comment by mattdesl** [comment]
Hmm to be honest I'm not totally sure why its incorrect, but I could be open to a PR to change this. Cheers!

**Comment by thednp** [comment]
Unfortunately I don't have the time to solve this and perhaps it's not even possible with the current `DOMMatrix()` draft. So I will close this for now, but if I ever find anything useful, YOU will be one of the first to know =)

**Comment by thednp** [comment]
Hello Matt @mattdesl 

As promised, I wanna share with you a script I found that nearly works, it has some flaws however, but out of all it's the only one that actually gets the rotation right; it doesn't do perspective right, the skewZ is something apparently, translation is off by ~0.5% and it adds some scale, given the same example I posted above.

https://gist.github.com/joelambert/1117818

I played with it for couple minutes and I found it an interesting idea, perhaps we can have a closer look when we have more time.
